### ISSUE TITLE
 MapTACheck failed due to TA check that is not accessible on linked account

### ISSUE THREAD

**Issue by fss18** [awslabs/aws-trusted-advisor-explorer#2]
## Problem:
I found that several newly launched TA checks are not accessible on the linked account level: '1qw23er45t', '1qazXsw23e', '7ujm6yhn5t', 'h3L1otH3re', 'vZ2c2W1srf', 'cX3c2R1chu'

This has caused the MapTACheck state machine failed to run.

StateMachine: MapTACheck
State: TARefresh
Log: [ERROR]	2020-05-30T19:22:35.386Z	1bab41fd-3806-4950-b759-574e6fbd2638	Unexpected client error An error occurred (LinkedAccountException) when calling the RefreshTrustedAdvisorCheck operation: Linked account is not able to access check vZ2c2W1srf

## Version
v1.0.0

**Comment by komarap** [comment]
Hello @fss18, Thank you for reporting this. We have rolled out a fix a for the same on May 19th. Please update your existing CloudFormation stack with the latest template available on the solution page (https://aws.amazon.com/solutions/aws-trusted-advisor-explorer/). Also, Please check the FAQ section for the checks supported by this solution.
